### ISSUE TITLE
Hard to build and install from code. Solution: publish premade DLL file

### ISSUE THREAD

**Issue by Omena0** [EchoHackCmd/Infernus-V2#5]
i have spent like 3 hours tryin to make this work

**Comment by MelihGMC2** [comment]
did you get it work?

**Comment by basedz** [comment]
this cheat is outdated ~~and arguably bad~~

**Comment by Omena0** [comment]
i didnt i hope some1 posts it in the discord

**Comment by zamilshebin8089** [comment]
hehe

**Comment by H3lix-Fire** [comment]
I think you're just dumb ngl

**Comment by Omena0** [comment]
No u r
